### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jwhsir** [meihaod/MydailyFudan#3]
运行报错，错误代码如下。请问是我部署的方式有问题吗？感谢！

Run python dailyFudan.py
Traceback (most recent call last):
  File "dailyFudan.py", line 107, in <module>
    if not login.check():
  File "dailyFudan.py", line 68, in check
    self.last_info = json.loads(self.session.get(url_get_info).text)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 1 (char 18)
Error: Process completed with exit code 1.

**Comment by meihaod** [comment]
建议先自己填一次，然后再运行。之后应该就没问题了

**Comment by jwhsir** [comment]
> 建议先自己填一次，然后再运行。之后应该就没问题了

感谢回复，我再试试！

**Comment by jwhsir** [comment]
已经尝试：（1）当天先手动填报，然后再手动运行一次actions；（2）前一天手动填报，第二天自动运行actions。但是问题依然存在，报错代码如下。

Run python dailyFudan.py
Traceback (most recent call last):
  File "dailyFudan.py", line 107, in <module>
    if not login.check():
  File "dailyFudan.py", line 68, in check
    self.last_info = json.loads(self.session.get(url_get_info).text)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 1 (char 18)
Error: Process completed with exit code 1.

请问是我部署的方式有问题吗？或者哪里的设置还需要调整？谢谢！！

**Comment by meihaod** [comment]
感觉json的解析问题，具体要查看你的json数据。要不你用别人的代码试试？
